import pandas as pd
from snakemake.utils import min_version
min_version("5.3.0")

configfile: "config/config.yaml"
samples = pd.read_table("config/samples.tsv").set_index("id", drop=False)
all_ids=list(samples["id"])

rule all:
    input:
        expand("{id}_1.fq.gz", id=all_ids),
        expand("{id}_2.fq.gz", id=all_ids)

rule build_organellar_genome_db:
    """
    Download and format Organellar Genomes from NCBI Organelle Genome Resources
    """
    output:
        "resources/org_genomes.fa", 
        expand("resources/org_genomes.fa.{ext}", ext=["ann", "bwt", "pac", "sa"])
    shell:
        """
        # dl refseq from ncbi
        wget -nd -np -r -A 'mitochondrion.*.*.genomic.fna.gz' ftp://ftp.ncbi.nlm.nih.gov/refseq/release/mitochondrion/
        wget -nd -np -r -A 'plastid.*.*.genomic.fna.gz' ftp://ftp.ncbi.nlm.nih.gov/refseq/release/plastid/

        # combine files
        gunzip -c *.fna.gz > resources/org_genomes.fa        

        # index with bwa
        bwa index resources/org_genomes.fa 
        
        # cleanup 
        rm mitochondrion.*.*.genomic.fna.gz
        rm plastid.*.*.genomic.fna.gz       
        """

rule link_fastq:
    """
    create symlink to file
    """
    input:
        fq1=lambda wildcards: samples.loc[wildcards.id, "fq1"],
        fq2=lambda wildcards: samples.loc[wildcards.id, "fq2"]
    output:
        "{id}_1.fq.gz",
        "{id}_2.fq.gz"
    shell:
        """
        cp {input.fq1} {output[0]}
        cp {input.fq2} {output[1]}
        """
        
#rule trim_reads_pe:
#    """
#    trim adapters and low quality sequence with trimmomatic for pe runs
#    """
#    input:
#        "{id}_1.fq.gz",
#        "{id}_2.fq.gz"

#    output:
#        "test.txt"
#        "{unique_id}_2.fq.gz"
 
#        "{unique_id}_1_trimmed.fq.gz",
#        "{unique_id}_1_trimmed_unpaired.fq.gz",
#        "{unique_id}_2_trimmed.fq.gz",
#        "{unique_id}_2_trimmed_unpaired.fq.gz"
#    params:
#        trim_params = config["trimming"]["trimmomatic_pe"]
#    shell:
#        """
#        trimmomatic PE {input[0]} {input[1]} \
#        {output[0]} {output[1]} \
#        {output[2]} {output[3]} \
#        ILLUMINACLIP:{FILE}:2:30:10 
#        """
