# Kmer-it config

sample_file: "config/samples.tsv"

## trimming options
trimming:
    enable: true # true | false
    trimmomatic_pe: "ILLUMINACLIP:resources/PE_all.fa:2:30:10 LEADING:5 TRAILING:5 SLIDINGWINDOW:4:20 MINLEN:36"
    trimmomatic_se: "ILLUMINACLIP:resources/SE_all.fa:2:30:10 LEADING:5 TRAILING:5 SLIDINGWINDOW:4:20 MINLEN:36"

## error correction options
error_correct:
    enable: true # true | false

## mapping options
map_to_organellar_genomes:
    enable: true # true | false
    use_custom_org_genome: true # true | false
    custom_org_genome_path: "genome.fa"

## K-mer to use
k: 6

## count normalization options
normalization:
    gc_correct: true # true | false
    cov_norm: true # true | false
    norm_method: "RLE"
