name: kmerit
channels:
- conda-forge
- bioconda
dependencies:
- bedtools=2.29.2
- bwa=0.7.17
- coreutils=8.25
- jellyfish=2.2.10
- samtools=1.11
- snakemake-minimal=5.31.1
- sra-tools=2.10.1
- trimmomatic=0.36
- wget=1.20.1
